import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "../globals.css";
import "./app.css"
import StoreNav from "../components/StoreNav";
import { UserStorage } from "../adminContext";
import { Suspense } from "react";
import Loading from "./loading";
import Footer from "../components/Footer";

const leagueSpartan = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home - PhonkSec",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={leagueSpartan.className}>
          <UserStorage>
            <Suspense fallback={<Loading/>}>  
                <StoreNav/>
                {children}    
                <Footer/>
            </Suspense>
          </UserStorage>
      </body>
    </html>
  );
}
