import React from 'react'
import { Metadata } from "next";
import styles from './page.module.css'

export const metadata: Metadata = {
    title: 'Home - Painel',
    description: "Generated by create next app",
}  

export default function page(){

 return (
    <main className={styles.painel}>
        <h2>Home</h2>
    </main>
  )
}
